name       : ibus-unikey
version    : 0.6.1
release    : 4
source     :
    - git|https://github.com/mrlequoctuan/ibus-unikey : af202789147262deec5e240f354dd8db29baa06e
license    : GPL-3.0-or-later
component  : desktop.core
summary    : Vietnamese Input Method Engine for IBus using Unikey Engine
description: |
    Vietnamese Input Method Engine for IBus using Unikey Engine
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(ibus-1.0)
    - pkgconfig(x11)
    - intltool
setup      : |
    %autogen --with-gtk-version=3
build      : |
    %make
install    : |
    %make_install
